# Generated by Django 4.2.3 on 2023-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('farmer_name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Fish & SeaFood', 'Fish & SeaFood')], max_length=30)),
                ('collected_food', models.DateTimeField(auto_now_add=True)),
                ('last_collected', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
